site_name: KinoML
site_description: Machine Learning for kinase modeling
site_url: https://openkinome.github.io/kinoml
repo_url: https://github.com/openkinome/kinoml
repo_name: openkinome/kinoml

# Edit below for the menus
nav:
  - Usage guide:
    - Home: index.md
    - Installation: install.md
    - Getting started: getting_started.md
  - Tutorials:
    - Example 1: tutorials/example.md
  - Development guide:
    - Base concepts: developers/api_concepts.md
    - How to write docs: developers/api_docs.md
  - API Reference:
      - kinoml: api/__init__.md
      - analysis: api/analysis/__init__.md
      - core:
        - complex: api/core/complex.md
        - conditions: api/core/conditions.md
        - ligand: api/core/ligand.md
        - measurements: api/core/measurements.md
        - protein: api/core/protein.md
      - datasets:
        - core: api/datasets/core.md
        - kinomescan:
          - pkis2: api/datasets/kinomescan/pkis2.md
          - utils: api/datasets/kinomescan/utils.md
      - docking: api/docking/__init__.md
      - features: api/features/__init__.md
      - ml: api/ml/__init__.md
      - modeling: api/modeling/__init__.md
      - optimize: api/optimize/__init__.md
      - workflows: api/workflows/__init__.md
      - utils: api/utils.md


# Do not modify below this line unless you _know_ what you are doing
theme:
  name: material
  logo:
    icon: bubble_chart
  favicon: assets/images/custom_favicon.png
  feature:
    tabs: true

extra_css:
  - assets/css/custom.css

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - git-revision-date-localized
  - minify:
      minify_html: true
  - mkdocstrings:
      watch:
        - kinoml
