site_name: KinoML
site_description: Machine Learning for kinase modeling
site_url: https://kinoml.github.io/
repo_url: https://github.com/openkinome/kinoml
repo_name: openkinome/kinoml

theme:
  name: "material"

extra_css:
  - css/custom.css


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences

plugins:
  - search
  - minify
  - mkdocstrings:
      watch:
        - kinoml

# Edit below for the menus
nav:
  - Home: index.md
  - Getting started: getting_started.md
  - Reference: api.md