name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Additional info about the build
      run: |
        uname -a
        df -h
        ulimit -a
    - name: Set up Miniconda
      run: |
        source devtools/scripts/install_miniconda.sh
        python -V
      env:
        OPERATING_SYSTEM: ${{ matrix.os }}
    - name: Create environment for package
      run: |
        python devtools/scripts/create_conda_env.py -n=test -p=${{ matrix.python-version }} devtools/conda-envs/test_env.yaml
        conda activate test
    - name: Install package
      run: pip install . --no-deps
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run tests
      run: pytest -v --cov=kinoml kinoml/tests/
    - name: Code coverage
      run: codecov